[project]
name = "{{ cookiecutter.module_name }}"
version = "0.1.0"
description = "{{ cookiecutter.description }}"
readme = "README.md"
requires-python = ">={{ cookiecutter.python_version }}"

dependencies = [
{%- if cookiecutter.datasets_type == "table" -%}
    "datasets>=2.0.0"
{%- elif cookiecutter.datasets_type == "vision" -%}
    "datasets[vision]>=2.0.0"
{%- endif -%}
]

[dependency-groups]
dev = ["mypy>=1.0.0", "pytest>=6.0.0", "ruff>=0.5.0"]

[tool.mypy]
python_version = "{{ cookiecutter.python_version }}"
ignore_missing_imports = true
