name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Check for TODO and FIXME
        run: |
          grep -n --exclude-dir={.git,.github} -rE "FIXME" | while read -r line
          do
              file=$(echo $line | cut -d: -f1)
              lineno=$(echo $line | cut -d: -f2)
              echo "::warning file=$file,line=$lineno::${line}"
          done

          if grep --exclude-dir={.git,.github} -rE "TODO"; then
              exit 1
          fi

      {%- raw %}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      {%- endraw %}

      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel poetry
          poetry install

      - name: Format
        run: |
          poetry run black --check .

      - name: Lint
        run: |
          poetry run ruff .

      - name: Type check
        run: |
          poetry run mypy .

      - name: Run tests
        run: |
          poetry run pytest --color=yes -rf
