name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install pytest-cookies

      - name: Run tests
        run: |
          pytest tests/

  format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: cookiecutter-huggingface-datasets

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -U cookiecutter ruff

      - name: Bake the project
        run: |
          cookiecutter ./cookiecutter-huggingface-datasets \
            --no-input \
            --config-file ./cookiecutter-huggingface-datasets/test_fixtures/config.yaml

      - name: Format
        run: |
          poetry run ruff format --check --diff huggingface-datasets_TestHfDataset

      - name: Lint
        run: |
          poetry run ruff check --output-format=github huggingface-datasets_TestHfDataset
